version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - .:/src
    command: sh -c "yarn install; yarn run dev"
    environment:
      - TZ=Asia/Tokyo
      - WATCHPACK_POLLING=true
