version: "3"

services:
  mypy:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/src
    tty: true
    ports:
      - 8000:8000
    environment:
      - DEV=true
      - TZ=Europe/London
    working_dir: /src
    command: bash -c "
      pipenv install &&
      cd api/ &&
      pipenv run uvicorn main:app --reload --host 0.0.0.0"
    links:
      - sql

  sql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypy
      MYSQL_USER: mypy
      MYSQL_PASSWORD: mypy
      TZ: Asia/Tokyo
