version: "3"

services:
  mypy:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/src
    tty: true
    ports:
      - 8000:8000
    command: bash -c "
      cd /src && pip install pipenv &&
      pipenv install &&
      . .venv/bin/activate &&
      uvicorn main:app --reload --host 0.0.0.0"
