version: "3"

services:
  gin-gonic:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/src
    tty: true
    ports:
      - 8000:8080
    environment:
      TZ: Asia/Tokyo
      MYSQL_HOST: sql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE_NAME: mypy
    working_dir: /src
    links:
      - sql

  sql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mypy
      MYSQL_USER: mypy
      MYSQL_PASSWORD: mypy
      TZ: Asia/Tokyo
