version: "3"

services:
  mypy:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/src
    tty: true
    ports:
      - 8000:8000
    working_dir: /src
    command: bash -c "
      pipenv install &&
      cd src/ &&
      pipenv run uvicorn main:app --reload --host 0.0.0.0"
