name: mypy and flake8

on:
  pull_request:
    paths:
      - backend/**
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  lint:
    defaults:
      run:
        working-directory: backend/

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip && pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install
        
      - name: Run mypy
        run: |
          pipenv run mypy --strict src/
      
      - name: Run flake8
        run: |
          pipenv run flake8 src/
