name: mypy and flake8

on:
  pull_request:
    paths:
      - backend/**
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  lint:
    defaults:
      run:
        working-directory: backend/

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install && pipenv install flake8

      - name: pwd and ls
        run: |
          pwd && ls -la

      - name: Activate pipenv
        run: |
          . $(pipenv --venv)/bin/activate
        
      - name: Run mypy
        run: |
          mypy --strict .
      
      - name: Run flake8
        run: |
          flake8 .
