name: mypy and flake8

on:
  pull_request:
    paths:
      - backend/**
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  lint:
    defaults:
      run:
        working-directory: backend/

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose up
        run: |
          docker compose -f "compose.lint.yml" up -d

      - name: Lint in docker compose
        run: |
          docker compose -f "./compose.lint.yml" exec mypy sh -c "
            cd /src && pip install pipenv &&
            pipenv install &&
            . .venv/bin/activate &&
            mypy --strict src/ &&
            flake8 src/"
